name: Build Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: |
          for example in $(ls ./_examples)
          do
            if [$example != "otel"]
            then
              echo "build $example"
              go build "./_examples/${example}"
            fi
          done

          for example in $(ls ./_examples/otel)
          do
            echo "build $example"
            go build "./_examples/otel/${example}"
          done
