name: Build Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.15
      - name: Test
        run: |
          for example in $(ls ./_examples)
          do
            echo "build $example"
            go build "./_examples/${example}"
          done
