name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version tag to release
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup git-chglog
        uses: zcong1993/setup-bin@v0.1.0
        with:
          name: git-chglog
          bin-version: v0.14.2
          download-url: https://github.com/git-chglog/git-chglog/releases/download/v0.14.2/git-chglog_0.14.2_linux_amd64.tar.gz
      - name: update changelog
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          VERSION=${{ github.event.inputs.version }}

          git-chglog --next-tag $VERSION -o CHANGELOG.md
          git commit -am "chore: update changelog for $VERSION"
          git tag $VERSION
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
